name: Nazwa pociągu
description: Zasugeruj nazwę pociągu
title: "[Sugestia - nazwa]: "
assignees:
  - Thundo
body:
  - type: markdown
    attributes:
      value: "Zanim zasugerujesz nową nazwę pociągu upewnij się, że taka nazwa już nie istnieje w [arkuszu tutaj](https://docs.google.com/spreadsheets/d/17twDH4Q7wx0pxrdQiUeB3Xc5Uo-zHarlV2QnuznSpH8/edit?usp=sharing)"
  - type: dropdown
    attributes:
      label: Przewoźnik
      description: Jakiego przewoźnika pociąg chcesz dodać?
      options:
        - Intercity
        - PolRegio
        - Koleje Śląskie
        - Koleje Małopolskie
        - Koleje Mazowieckie
        - Koleje Dolnośląskie
        - Łódzka Kolej Aglomeracyjna
    validations:
      required: true
  - type: input
    attributes:
      label: Inny przewoźnik
      description: Jeżeli w polu powyżej wybrałeś **None**, uzupełnij to pole o nazwę przewoźnika, a także jego skrót, jeśli istnieje
    validations:
      required: false
  - type: input
    attributes:
      label: Numery pociągu
      description: Wypisz po przecinku wszystkie występujące dla tej nazwy pociągu numery
      placeholder: 1620, 6120
    validations:
      required: true
  - type: input
    attributes:
      label: Nazwa pociągu
      description: W tym miejscu wpisz nazwę pociągu jaka ma być wyświetlana na tablicach
      placeholder: Asnyk
    validations:
      required: true
  - type: input
    attributes:
      label: Nadpisane kategorii
      description: Jeżeli pociąg w rzeczywistości ma inną kategorię handlową niż mogłaby mu być przypisana przez skrypt tablic uzupełnij to pole
      placeholder: EIC
    validations:
      required: false
  - type: textarea
    attributes:
      label: Informacje o pociągu
      description: Dodaj infomacje o pociągu (m.in. potwierdzające nazwę pociągu)
    validations:
      required: true
